/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.lang.reflect.Array;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sistemas-08
 */
public class FrmFne extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form FrmFne
     */
    public FrmFne() {
        initComponents();
        tbContent.setModel(model);
//        String titu[] = {"Inversion","Ingresos","Egresos","Depreciacion","VS","U.A.I","IR","I.D.I","Depreciacion","FNE"};
//        model.addColumn(titu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlButtom = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtVPN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPR = new javax.swing.JTextField();
        pnlIN = new javax.swing.JPanel();
        pnlInput = new javax.swing.JPanel();
        txtInversion = new javax.swing.JTextField();
        txtIngresos = new javax.swing.JTextField();
        txtPlazo = new javax.swing.JTextField();
        txtEgresos = new javax.swing.JTextField();
        txtVS = new javax.swing.JTextField();
        txtInflacion = new javax.swing.JTextField();
        txtTasa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pnlTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbContent = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        jLabel1.setText("VPN:");

        jLabel2.setText("PR:");

        javax.swing.GroupLayout pnlButtomLayout = new javax.swing.GroupLayout(pnlButtom);
        pnlButtom.setLayout(pnlButtomLayout);
        pnlButtomLayout.setHorizontalGroup(
            pnlButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtomLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(txtVPN, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(txtPR, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        pnlButtomLayout.setVerticalGroup(
            pnlButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtomLayout.createSequentialGroup()
                .addGroup(pnlButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlButtomLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(pnlButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btnCrear)))
                    .addGroup(pnlButtomLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtVPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlButtomLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2))
                    .addGroup(pnlButtomLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2))
        );

        getContentPane().add(pnlButtom, java.awt.BorderLayout.PAGE_END);

        pnlIN.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Inversion");

        jLabel4.setText("Ingresos");

        jLabel5.setText("Egresos");

        jLabel6.setText("Plazo");

        jLabel7.setText("Tasa");

        jLabel8.setText("Inflacion");

        jLabel9.setText("Valor de Salvamento");

        javax.swing.GroupLayout pnlInputLayout = new javax.swing.GroupLayout(pnlInput);
        pnlInput.setLayout(pnlInputLayout);
        pnlInputLayout.setHorizontalGroup(
            pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputLayout.createSequentialGroup()
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInputLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPlazo)
                            .addComponent(txtInversion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIngresos, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTasa, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInflacion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVS, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEgresos, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(pnlInputLayout.createSequentialGroup()
                        .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInputLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel3))
                            .addGroup(pnlInputLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel4))
                            .addGroup(pnlInputLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel5))
                            .addGroup(pnlInputLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jLabel7))
                            .addGroup(pnlInputLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel6))
                            .addGroup(pnlInputLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel8)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInputLayout.createSequentialGroup()
                .addGap(0, 38, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(36, 36, 36))
        );
        pnlInputLayout.setVerticalGroup(
            pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtInversion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtEgresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(txtPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txtTasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(txtInflacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(txtVS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pnlIN.add(pnlInput, java.awt.BorderLayout.LINE_START);

        pnlTable.setLayout(new java.awt.BorderLayout());

        tbContent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbContent);

        pnlTable.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnlIN.add(pnlTable, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlIN, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        loadTable();
    }//GEN-LAST:event_btnCrearActionPerformed

    private double redondear(double num) {
        return Math.rint(num * 100) / 100;
    }

    private void loadTable() {
        if (txtInversion.getText().isBlank() || txtInversion.getText().isBlank() || txtEgresos.getText().isBlank() || txtPlazo.getText().isBlank() || txtTasa.getText().isBlank() || txtInflacion.getText().isBlank() || txtVS.getText().isBlank()) {
            JOptionPane.showInputDialog(null, "Todos los campos son obligatorios, porfavor Llenarlos adecuadamente");
            return;
        } else {
            int plazo = Integer.parseInt(txtPlazo.getText());
            int inflacion = Integer.parseInt(txtInflacion.getText());
            double depreciacion = (Double.parseDouble(txtInversion.getText()) - Double.parseDouble(txtVS.getText())) / plazo;
            double valorSalvamento = Double.parseDouble(txtVS.getText());
            String[] fne = new String[plazo + 1];
            fne[0] = txtInversion.getText();

            model.addColumn(" ");
            for (int i = 1; i <= plazo; i++) {
                model.addColumn("  " + i);
            }

            //------------------------------------
            String rowData[] = new String[plazo];
            rowData[0] = "Inversion";
            rowData[1] = txtInversion.getText();
            //------------------------------------
            String rowData1[] = new String[plazo + 1];

            rowData1[0] = "Ingresos";
            rowData1[1] = txtIngresos.getText();
            Double ingresos = (Double.parseDouble(rowData1[1]) * inflacion);
            ingresos = redondear(ingresos);
            fne[1] = ingresos.toString();
            for (int i = 2; i <= plazo; i++) {
                rowData1[i] = ingresos.toString();
                
                String ingresosFne = String.valueOf(inflacion);
                Double ingresosFNEi = (Double.parseDouble(ingresosFne));
                int ingresosFneIneger = Integer.parseInt(ingresosFne);

//                fne[i] = ingresosFneIneger. * (inflacion/100);
            }
            
            //------------------------------------
            String rowData2[] = new String[plazo + 2];
            
            rowData2[0] = "Egresos";
            rowData2[1] = txtEgresos.getText();
            Double egresos = (Double.parseDouble(rowData2[1]) * inflacion);
            ingresos = redondear(ingresos);
            for (int i = 2; i <= plazo; i++) {
                rowData2[i] = egresos.toString();
            }
            //------------------------------------
            String rowData3[] = new String[plazo + 3];
            rowData3[0] = "Depreciacion";
            depreciacion = redondear(depreciacion);
            rowData3[1] = String.valueOf(depreciacion);
            for (int i = 2; i <= plazo; i++) {
                rowData3[i] = String.valueOf(depreciacion);
            }
            //------------------------------------
            String rowData4[] = new String[plazo + 4];
            rowData4[0] = "Valor de Salvamento";
            valorSalvamento = redondear(valorSalvamento);
            for (int i = 1; i <= plazo; i++) {
                if (i == plazo) {
                    rowData4[i] = String.valueOf(valorSalvamento);
                }else{
                    rowData4[1 + i] = "-";
                }
            }
            //------------------------------------
            String rowData5[] = new String[plazo + 5];
            rowData5[0] = "U.A.I";
            
            
            //Quede hasta Utilidad antees de Impuesto
            model.addRow(rowData);
            model.addRow(rowData1);
            model.addRow(rowData2);
            model.addRow(rowData3);
            model.addRow(rowData4);
            model.addRow(rowData5);
        }
//        for (int i = 0; i < txtPlazo.getText(); i++) {
//            
//        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlButtom;
    private javax.swing.JPanel pnlIN;
    private javax.swing.JPanel pnlInput;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JTable tbContent;
    private javax.swing.JTextField txtEgresos;
    private javax.swing.JTextField txtInflacion;
    private javax.swing.JTextField txtIngresos;
    private javax.swing.JTextField txtInversion;
    private javax.swing.JTextField txtPR;
    private javax.swing.JTextField txtPlazo;
    private javax.swing.JTextField txtTasa;
    private javax.swing.JTextField txtVPN;
    private javax.swing.JTextField txtVS;
    // End of variables declaration//GEN-END:variables
}
